title:              My Data Science Collection | Projects, Insights & Experiments
email:              dfahim7@gmail.com
description:        A personal collection of data science projects, analyses, and experiments. Featuring work in Python, machine learning, data visualization, and more.
author:             Danial Fahim
baseurl:            "/My-Data-Science-Collection"
url:                "https://dfbaf.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
